name: learn_qiskit
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2022.07.19
  - certifi=2022.6.15
  - intel-openmp=2021.4.0
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.0.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - numpy-base=1.23.1
  - openssl=1.1.1q
  - python=3.10.4
  - readline=8.1.2
  - setuptools=63.4.1
  - six=1.16.0
  - sqlite=3.39.2
  - tk=8.6.12
  - tzdata=2022a
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - pip:
    - cffi==1.15.1
    - charset-normalizer==2.1.1
    - cryptography==37.0.4
    - dill==0.3.5.1
    - idna==3.3
    - mpmath==1.2.1
    - ntlm-auth==1.5.0
    - numpy==1.23.2
    - pbr==5.10.0
    - pip==22.2.2
    - ply==3.11
    - psutil==5.9.1
    - pycparser==2.21
    - python-dateutil==2.8.2
    - qiskit==0.37.2
    - qiskit-aer==0.10.4
    - qiskit-ibmq-provider==0.19.2
    - qiskit-terra==0.21.2
    - requests==2.28.1
    - requests-ntlm==1.1.0
    - retworkx==0.11.0
    - scipy==1.9.0
    - stevedore==4.0.0
    - symengine==0.9.2
    - sympy==1.11
    - tweedledum==1.1.1
    - urllib3==1.26.12
    - websocket-client==1.4.0
    - websockets==10.3
